FROM jamesmcclain/jupyter-geopyspark:centos-build-base

COPY blobs/gcc-6.4.0-33.x86_64.rpm /blobs/gcc-6.4.0-33.x86_64.rpm

RUN yum remove -y gcc-c++ && \
    yum localinstall -y /blobs/gcc-6.4.0-33.x86_64.rpm && \
    ln -s /usr/local/bin/gcc /usr/local/bin/cc
